.\" Manuel pour la bilbiothèque Satellite
.TH Satellite 1 "20/07/2020" "Version 1.0" "Manuel Satellite"

.SH NOM
.B Satellite

.SH TYPE
.B Bibliothèqe Bash

.SH DESCRIPTION
Satellite permet de récuperer une image satellite

.SH SYNOPSYS
.B Inclusion de la bibliothèque :  source $UTILS



.SH COMMANDE GetImage
.B Description
GetImage vous permet de récuperer une image satellite de l'Europe au format .png
.TP
Cette bibliothèques utilise une API en ligne
.B Option(s)
'emplacement de l'image sauvegardée et son nom, sans l'extension de l'image
.B Retour : Rien
.B Exemple
GetImage $HOME/img_sat



.SH VOIR AUSSI
source
.SH AUTHOR \n
Nicolas Le Guerroué - nicolasleguerroue@gmail.com

