.\" Manuel pour la bilbiothèque System
.TH System 1 "20/07/2020" "Version 1.0" "Manuel System"

.SH NOM
.B System

.SH TYPE
.B Bibliothèqe Bash

.SH DESCRIPTION
.I System vous permet de récuperer des informations sur l\'ordinateur  


.SH COMMANDES GetUser, GetShell, GetSession, GetStartTime, GetTimeActivity, GetNumberUsers

.SH SYNOPSYS
.B Inclusion de la bibliothèque :  source $UTILS



.SH COMMANDE GetUser

.B Description
Permet de récuperer le nom de l\'utilisateur  

.B Option(s)
Aucun argument attendu

.B Retour : Rien

.B Exemple
echo GetUser


.SH COMMANDE GetShell



.B Description
Permet de récuperer le nom du shell 

.B Option(s)
Aucun argument attendu

.B Retour : Rien

.B Exemple
source $UTILS && echo GetShell



.SH COMMANDE GetSession

.B Description
Permet de récuperer le nom de la session

.B Option(s)
Aucun argument attendu


.B Retour : Rien

.B Exemple
echo GetSession



.SH COMMANDE GetSessionType

.B Description
Permet de récuperer le type de la session

.B Option(s)
Aucun argument attendu

.B Retour : Rien

.B Exemple
echo GetSessionType





.SH COMMANDE GetStartTime


.B Description
Permet de récuperer l\'heure du démarrage de l\'ordinateur

.B Option(s)
Aucun argument attendu

.B Retour : Rien

.B Exemple
echo GetStartTime




.SH COMMANDE GetTimeActivity


.B Description
Permet de récuperer le temps écoulé depuis le démarrage de l\'ordinateur.

.B Option(s)
Aucun argument attendu

.B Retour : Rien

.B Exemple
echo GetTimeActivity



.SH COMMANDE GetNumberUsers


.B Description
Permet de récuperer le nombre d\'utilisateurs connectés à l\'ordinateur

.B Option(s)
Aucun argument attendu

.B Retour : Rien

.B Exemple
echo GetNumberUsers





.SH VOIR AUSSI
source

.SH AUTHOR 
Nicolas Le Guerroué - nicolasleguerroue@gmail.com

