.\" Manuel pour la bilbiothèque Time
.TH Time 1 "20/07/2020" "Version 1.0" "Manuel Time"

.SH NOM
.B Time

.SH TYPE
.B Bibliothèqe Bash

.SH DESCRIPTION
.I Time vous permet de récuperer les informations du temps


.SH COMMANDES GetTime, GetYear, GetMonth, GetDay, GetHour, GetMinute, GetSeconde

.SH SYNOPSYS
.B Inclusion de la bibliothèque :  source $UTILS


.SH COMMANDE GetTime

.B Description
Permet de récuperer le temps

.B Option(s)
Aucun argument attendu

.B Retour : Rien

.B Exemple
echo GetTime



.SH COMMANDE getYear

.B Description
Permet de récuperer l\'année

.B Option(s)
Aucun argument attendu

.B Retour : Rien

.B Exemple
echo getYear


.SH COMMANDE GetMonth

.B Description
Permet de récuperer le mois

.B Option(s)
Aucun argument attendu

.B Retour : Rien

.B Exemple
echo GetMonth



.SH COMMANDE GetDay

.B Description
Permet de récuperer le jour

.B Option(s)
Aucun argument attendu

.B Retour : Rien

.B Exemple
echo GetDay



.SH COMMANDE GetHour

.B Description
Permet de récuperer l\'heure

.B Option(s)
Aucun argument attendu

.B Retour : Rien

.B Exemple
echo GetHour



.SH COMMANDE GetMinute

.B Description
Permet de récuperer les minutes

.B Option(s)
Aucun argument attendu

.B Retour : Rien

.B Exemple
echo GetMinute



.SH COMMANDE GetSeconde

.B Description
Permet de récuperer les secondes

.B Option(s)
Aucun argument attendu

.B Retour : Rien

.B Exemple
echo GetSeconde



.SH VOIR AUSSI
source
.SH AUTHOR \n
Nicolas Le Guerroué - nicolasleguerroue@gmail.com

