.\" Manuel pour la bilbiothèque utils-tree
.TH utils-tree 1 "20/07/2020" "Version 1.0" "Manuel utils-tree"

.SH NOM
.B utils-tree



.SH TYPE
.B Bibliothèqe Bash

.SH DESCRIPTION
.I utils-tree vous permet de récuperer l\'arborescence du dossier Utils


.SH SYNOPSYS
.B Inclusion de la bibliothèque :  source $UTILS



.SH COMMANDE
utils-tree 
..B Description 
utils-tree vous permet \'afficher \'arborescence du dossier Utils
.B Option(s)
Aucun argument attendu
.B Retour : Rien
.B Exemple
utils-tree

.SH VOIR AUSSI
source

.SH AUTHOR \n
Nicolas Le Guerroué - nicolasleguerroue@gmail.com

