.\" Manuel pour la bilbiothèque utils-hardinfo
.TH utils-hardinfo 1 "20/07/2020" "Version 1.0" "Manuel utils-hardinfo"

.SH NOM
.B utils-hardinfo


.SH TYPE
.B Bibliothèqe Bash

.SH DESCRIPTION
.I Time vous permet de récuperer les informations du temps


.SH SYNOPSYS
.B Inclusion de la bibliothèque :  source $UTILS


.SH COMMANDE
utils-hardinfo 
..B Description 
utils-hardinfo vous permet \'afficher les informations du matériel (mémoire, disques, ports...)
.B Option(s)
Aucun argument attendu
.B Retour : Rien
.B Exemple
utils-hardinfo

.SH VOIR AUSSI
source

.SH AUTHOR \n
Nicolas Le Guerroué - nicolasleguerroue@gmail.com

