#!/bin/bash
if [[ $1 == "" ]]; then
	echo "Veuillez préciser une adresse IP. (raspberry-pi)"
	exit
fi

gst-launch-1.0 -v tcpclientsrc host=$1 port=5000 ! gdpdepay ! rtph264depay ! avdec_h264 ! videoconvert  ! autovideosink sync=false