#!/bin/bash
# $1 is input filename
# $2 is output filename
echo -e "Start converting color to grey"

if [[ $1 == "" ]]; then
	echo "Please select a file to convert from color to grey"
	exit
fi
if [[ $2 == "" ]]; then
	echo "Please select an output filename"
	exit
fi

echo "Please select a file to convert from color to grey"

convert $1 -colorspace Gray $2

