#!/bin/bash
# $1 is folder-name
# $2 is new generic name
echo -e "Start rename of files into $1"

i=1
for file in `ls $1`; do
	echo "Rename of '$file' by '"$2_$i"'"
	mv `pwd`/$1/$file `pwd`/$1/$2_$i
	i=$((i+1))
done

