.\" Manuel pour la commande image-grey
.TH image-grey 7 "10/12/2020" "Version 1.0" "Manuel Colors"

.SH NOM
.B image-grey

.SH DESCRIPTION

image-grey permet de modifier la couleur d'une image pour la mettre en noir et blanc.

.SH TYPE
Commande Bash

.SH SYNOPSYS
.B Inclusion de la bibliothèque :  source $UTILS


.SH ARGUMENT(s)

.TP
Nom de l'image d\'entrée
.TP
Nom de l'image de sortie

.SH OPTIONS
Aucune option

.SH EXEMPLE
image-grey img1.png img2.png

.SH VOIR AUSSI
source
.SH ERREURS 

.SH AUTHOR
Nicolas Le Guerroué - nicolasleguerroue@gmail.com
